---
title: "Distributive Fairness Appeals: Equality, Reciprocity, or Need"
output: 
  html_document:
    toc: false
    toc_depth: 4
    code_folding: hide
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(dplyr)
library(PerformanceAnalytics)
library(kableExtra)
library(psych)
library(ggplot2)
library(jmv)
library(magick)
library(report)
library(reshape2)
library(ordinal)
library(RVAideMemoire)
library(emmeans)
library(effectsize)
library(repmod)
library(MANOVA.RM)
library(ggrepel)
library(matrixTests)
library(tidyverse)
library(lessR)
library(rstatix)
library(multcomp)
library(jtools)
library(sjPlot)




set.seed(42)

options(scipen=999, digits=3)

#This function concatenates multiple vectors element-wise while handling NA values by replacing them with empty strings.
#Works like paste(), but ensures that NA values are treated as missing (not "NA" as paste() would normally do).
#Removes unnecessary spaces or separators from the output.
#Converts empty results back to NA.

paste_na <- function(..., sep = " ") {
  L <- list(...)
  L <- lapply(
    L,
    function(x) {
      x[is.na(x)] <- ""
      x
    }
  )
  out <- gsub(
    paste0("(^", sep, "|", sep, "$)"), "",
    gsub(
      paste0(sep, sep), sep,
      do.call(paste, c(L, list(sep = sep)))
    )
  )
  is.na(out) <- out == ""
  return(out)
}
```

Materials, data, code accompanying the article "Equality, Reciprocity, or Need? Bolstering Welfare Policy Support for Marginalized Groups with Distributive Fairness". 

# Study 2 {.tabset}
## Data {.tabset}
### Data load
```{r}

s2 <- import("/Users/bellamullen/Documents/GITHUB/Findor2023_Replication/original_materials/data/Study2.sav")

```

### Data prep
```{r, message=FALSE, results='hide'}
s2$home= factor(s2$home, levels = c(1, 2,3,4), labels = c("home-answered","away-notanswered","home-return", "away-return"))
s2$consent= factor(s2$consent, levels = c(1, 2), labels = c("yes","no"))
s2$etnic_ascr= factor(s2$etnic_ascr, levels = c(1, 2), labels = c("slovak","roma"))
s2$etnicita= factor(s2$etnicita, levels = c(1, 2,3), labels = c("slovak","roma","other"))
s2$age <- as.numeric(s2$age)
s2 <- lessR::recode(age, new_vars="roky_", old=9:72, new=1996:1933, data=s2)
s2$years <- 2019 - s2$roky
s2$gender <- factor(s2$gender, levels = c(1, 2), labels = c("Male","Female"))
s2_consent <- dplyr::filter(s2, consent=="yes")
s2_consent <- dplyr::filter(s2_consent, etnic_ascr != "NA")
s2_consent <- dplyr::filter(s2_consent, eurofondy_iv<5 & skolka_iv<5 & skolka_agree<5 & skolka_vote<5 & skolka_norms < 5 & control < 5 & suma < 5 & praca < 5 & potreba<5 & pila <5 )
```

## Descriptives {.tabset}
### Main outcomes {.tabset}
```{r}
s2_consent %>% dplyr::group_by(etnic_ascr) %>% dplyr::summarise(N = length(control), Min=min(control,na.rm= TRUE),Q1 = quantile(control,probs = .25,na.rm = TRUE),Median = median(control, na.rm = TRUE),Q3 = quantile(control,probs = .75,na.rm = TRUE),Max = max(control,na.rm = TRUE),Mean = mean(control, na.rm = TRUE),SD = sd(control, na.rm = TRUE), Skew = skewness(control, na.rm = TRUE), Kurtosis = kurtosis(control, na.rm = TRUE)) -> s2_control

knitr::kable(s2_control, caption = "Study 2 - control")%>%
  kable_styling(full_width = F)


s2_consent %>% dplyr::group_by(etnic_ascr) %>% dplyr::summarise(N = length(suma), Min=min(suma,na.rm= TRUE),Q1 = quantile(suma,probs = .25,na.rm = TRUE),Median = median(suma, na.rm = TRUE),Q3 = quantile(suma,probs = .75,na.rm = TRUE),Max = max(suma,na.rm = TRUE),Mean = mean(suma, na.rm = TRUE),SD = sd(suma, na.rm = TRUE), Skew = skewness(suma, na.rm = TRUE), Kurtosis = kurtosis(suma, na.rm = TRUE)) -> s2_equal

knitr::kable(s2_equal, caption = "Study 2 - equality")%>%
  kable_styling(full_width = F)

s2_consent %>% dplyr::group_by(etnic_ascr) %>% dplyr::summarise(N = length(praca), Min=min(praca,na.rm= TRUE),Q1 = quantile(praca,probs = .25,na.rm = TRUE),Median = median(praca, na.rm = TRUE),Q3 = quantile(praca,probs = .75,na.rm = TRUE),Max = max(praca,na.rm = TRUE),Mean = mean(praca, na.rm = TRUE),SD = sd(praca, na.rm = TRUE), Skew = skewness(praca, na.rm = TRUE), Kurtosis = kurtosis(praca, na.rm = TRUE)) -> s2_prop

knitr::kable(s2_prop, caption = "Study 2 - proportionality")%>%
  kable_styling(full_width = F)

s2_consent %>% dplyr::group_by(etnic_ascr) %>% dplyr::summarise(N = length(potreba), Min=min(potreba,na.rm= TRUE),Q1 = quantile(potreba,probs = .25,na.rm = TRUE),Median = median(potreba, na.rm = TRUE),Q3 = quantile(potreba,probs = .75,na.rm = TRUE),Max = max(potreba,na.rm = TRUE),Mean = mean(potreba, na.rm = TRUE),SD = sd(potreba, na.rm = TRUE), Skew = skewness(potreba, na.rm = TRUE), Kurtosis = kurtosis(potreba, na.rm = TRUE)) -> s2_need

knitr::kable(s2_need, caption = "Study 2 - need")%>%
  kable_styling(full_width = F)

```

```{r}

s2_consent <- mutate(s2_consent, ID = row_number())

s2_mains <- melt(s2_consent,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c("etnic_ascr", "ID","eurofondy_iv","skolka_iv" ),
        # The source columns
    measure.vars=c("control", "suma", "praca","potreba","pila"),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name="condition",
    value.name="measurement"
)

s2_mains <- filter(s2_mains, condition!="pila") 

s2_dvs <- s2_mains %>%
  group_by(etnic_ascr,condition)%>%
  dplyr::select(-ID:-skolka_iv) %>%
  get_summary_stats(type = c("mean_sd"))%>%
  dplyr::select(-variable)%>%
  dplyr::mutate(condition = dplyr::recode(condition,
    "control" = "Control",
    "suma" = "Equality",
    "praca" = "Reciprocity",
    "potreba" = "Need"))%>%
  dplyr::mutate(sd = round(sd,2))
      

dvstt <- s2_mains %>% 
#  pivot_longer(contains("att_"))%>% 
    group_by(etnic_ascr)%>% 
    t_test(measurement~condition, detailed = T)      

```


### Sample characteristics
```{r}
s2_consent_gender <- s2_consent %>% group_by(gender) %>% 
dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n))
s2_consent_gender$freq <- round(s2_consent_gender$freq, 3)

s2_consent_gender%>%
kable(caption = "Gender")%>%
  kable_styling(full_width = F)

s2_consent_age <- s2_consent %>% dplyr::summarise(Min=min(years,na.rm= TRUE),Q1 = quantile(years,probs = .25,na.rm = TRUE),Median = median(years, na.rm = TRUE),Q3 = quantile(years,probs = .75,na.rm = TRUE),Max = max(years,na.rm = TRUE),Mean = round(mean(years, na.rm = TRUE),3),SD = round(sd(years, na.rm = TRUE),2),n = n(),Missing = sum(is.na(years))) 

s2_consent_age %>%
  kable(caption = "Age") %>%
  kable_styling(full_width = F)

s2_consent_etnic <- s2_consent %>% group_by(etnic_ascr) %>% 
dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n))
s2_consent_etnic$freq <- round(s2_consent_etnic$freq, 3)

s2_consent_etnic%>%
kable(caption = "Ascribed ethnicity")%>%
  kable_styling(full_width = F)

s2_consent_etnic_self <- s2_consent %>% group_by(etnicita) %>% 
dplyr::summarise(n = n()) %>%
  mutate(freq = n / sum(n))
s2_consent_etnic_self$freq <- round(s2_consent_etnic_self$freq, 3)

s2_consent_etnic_self%>%
kable(caption = "Self-reported ethnicity")%>%
  kable_styling(full_width = F)
```

## Plots {.tabset}
### Main outcomes

## Main analysis {.tabset}
```{r}
s2_mains$condition <- dplyr::recode(s2_mains$condition, suma = "equal", praca = "reciprocity", potreba="need", control = "control")
s2_mains$measurement <- as.factor(s2_mains$measurement)

model <- clmm(measurement ~ condition * etnic_ascr + (1|ID),data = s2_mains, threshold = "equidistant", Hess = T)
summary(model)
Anova.clmm(model, type = "II")

emmip <- emmip(model, condition ~ etnic_ascr, CIs = T, engine = "ggplot",style = "factor", plotit = F, mode= "mean.class")

names(emmip)[8] <- "Condition"
emmip$Condition <- dplyr::recode(emmip$Condition , 'control' = "Control", "reciprocity" = 'Reciprocity', "need" = 'Need', "equal" = 'Equality')
emmip$xvar <- dplyr::recode(emmip$xvar , 'slovak' = "Slovak", "roma" = 'Roma')

(emmplot <- ggplot(data = emmip, aes(y= yvar, x = xvar, group = Condition)) + geom_point(size=1.3, position=position_dodge(width=0.1), aes(color = Condition)) + #geom_line(size=1.3,position=position_dodge(width=0.1),aes(linetype=Condition, color=Condition))+  
    geom_linerange(size=1.3,aes(x = xvar,
                     ymin = LCL,
                     ymax = UCL, color = Condition),
                 show.legend = FALSE,position=position_dodge(width=0.1))+
    scale_color_grey(start = 0.2, end = 0.7) +
    scale_fill_grey(start = 0.2, end = 0.7)+theme_classic()  + labs(y = "Predicted average agreement", x = 'Ascribed ethnicity') +
  geom_text_repel(aes(label = Condition, colour = Condition),
    data          = subset(emmip, xvar == "Slovak"),
    nudge_x       = -0.25,
    segment.size  = 0.2,
    direction     = "y") +
  geom_text_repel(aes(label = Condition, colour = Condition),
    data          = subset(emmip, xvar == "Roma"),
    nudge_x       = 0.25,
    segment.size  = 0.2,
    direction     = "y") + theme(legend.position="none")+
  scale_linetype_manual(values=c("twodash", "dotted","longdash", "solid" ))+
    theme(text = element_text(size=15)) + ylim(1,4) )

#ggsave("plot.png", width = 6, height = 5)

emmip%>%
kable(caption = "Predicted average agreement")%>%
  kable_styling(full_width = F)
```
```{r}
library(nnet)
model_glm <- multinom(measurement ~ condition * etnic_ascr + (1|ID),data = s2_mains, threshold = "equidistant", Hess = T, family= "binomial"(link='probit'))
summary(model_glm)
```

